-- ===============================================================
-- SERRE KAS 8 (DESERT JOY) - SCHÉMA COMPLET SUPABASE
-- À exécuter dans : Supabase Dashboard > SQL Editor > New Query
-- ===============================================================

-- 1. Table 'settings' (Configuration de la serre et des superviseurs)
CREATE TABLE IF NOT EXISTS public.settings (
    id INT PRIMARY KEY DEFAULT 1,
    gauche_start INT DEFAULT 1,
    gauche_end INT DEFAULT 140,
    droit_start INT DEFAULT 1,
    droit_end INT DEFAULT 140,
    sup1_name TEXT DEFAULT 'Supervisor 1',
    sup2_name TEXT DEFAULT 'Supervisor 2',
    sup1_pwd TEXT DEFAULT '',
    sup2_pwd TEXT DEFAULT '',
    admin_pwd TEXT DEFAULT '1234',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on settings" ON public.settings;
CREATE POLICY "Allow public read access on settings" ON public.settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access on settings" ON public.settings;
CREATE POLICY "Allow public write access on settings" ON public.settings FOR ALL USING (true);

-- Initialisation configuration par défaut
INSERT INTO public.settings (id, gauche_start, gauche_end, droit_start, droit_end, sup1_name, sup2_name, admin_pwd)
VALUES (1, 1, 140, 1, 140, 'Supervisor 1', 'Supervisor 2', '1234')
ON CONFLICT (id) DO NOTHING;


-- 2. Table 'wip' (Brouillons & état en cours instantané)
CREATE TABLE IF NOT EXISTS public.wip (
    id TEXT PRIMARY KEY,
    gauche_state JSONB DEFAULT '{}'::jsonb,
    droit_state JSONB DEFAULT '{}'::jsonb,
    remarks TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.wip ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on wip" ON public.wip;
CREATE POLICY "Allow public read access on wip" ON public.wip FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access on wip" ON public.wip;
CREATE POLICY "Allow public write access on wip" ON public.wip FOR ALL USING (true);


-- 3. Table 'submissions' (Historique des pointages validés)
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    supervisor TEXT NOT NULL,
    week TEXT NOT NULL,
    task TEXT NOT NULL,
    gauche_count INT DEFAULT 0,
    droit_count INT DEFAULT 0,
    total_max INT DEFAULT 280,
    remarks TEXT DEFAULT '',
    gauche_state JSONB DEFAULT '{}'::jsonb,
    droit_state JSONB DEFAULT '{}'::jsonb,
    gauche_range JSONB DEFAULT '{"start":1,"end":140}'::jsonb,
    droit_range JSONB DEFAULT '{"start":1,"end":140}'::jsonb
);

ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on submissions" ON public.submissions;
CREATE POLICY "Allow public read access on submissions" ON public.submissions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access on submissions" ON public.submissions;
CREATE POLICY "Allow public write access on submissions" ON public.submissions FOR ALL USING (true);


-- 4. Table 'trolleys' (Suivi des 42 Chariots & Planning de Charge)
CREATE TABLE IF NOT EXISTS public.trolleys (
    id INT PRIMARY KEY,
    worker TEXT DEFAULT '',
    pins_assigned INT DEFAULT 10,
    pins_found INT DEFAULT 10,
    charge_status TEXT DEFAULT 'Normale',
    charge_pct INT DEFAULT 100,
    charge_day TEXT DEFAULT 'Lundi',
    charger_num TEXT DEFAULT 'Chargeur 1',
    notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.trolleys ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on trolleys" ON public.trolleys;
CREATE POLICY "Allow public read access on trolleys" ON public.trolleys FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public write access on trolleys" ON public.trolleys;
CREATE POLICY "Allow public write access on trolleys" ON public.trolleys FOR ALL USING (true);

-- Initialisation des 42 chariots
INSERT INTO public.trolleys (id, worker, pins_assigned, pins_found, charge_status, charge_pct, charge_day, charger_num)
SELECT 
    i,
    '',
    10,
    10,
    'Normale',
    100,
    CASE ((i - 1) % 7)
        WHEN 0 THEN 'Lundi'
        WHEN 1 THEN 'Mardi'
        WHEN 2 THEN 'Mercredi'
        WHEN 3 THEN 'Jeudi'
        WHEN 4 THEN 'Vendredi'
        WHEN 5 THEN 'Samedi'
        ELSE 'Dimanche'
    END,
    'Chargeur ' || (((i - 1) % 10) + 1)
FROM generate_series(1, 42) AS i
ON CONFLICT (id) DO NOTHING;
